name: clang-format check

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  formatting-check:
    name: Formatting Check
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run clang-format style check for C/C++ programs.
      uses: jidicula/clang-format-action@v4.0.0
      with:
        clang-format-version: '12'
        check-path: 'src'
        fallback-style: 'Google'

