name: Ubuntu

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  ci_test_compilers:
    runs-on: ubuntu-latest
    container: nlohmann/json-ci:latest
    strategy:
      matrix:
        compiler: [g++-5, g++-7, g++-8, g++-9, g++-10, g++-11, clang++-6.0, clang++-7, clang++-8, clang++-9, clang++-10, clang++-11]
    steps:
      - uses: actions/checkout@v2
      - name: Install compiler
        run: |
          apt-get update
          apt-get install -y ${{ matrix.compiler }} 
      - name: cmake
        run: cmake -S . -B build -DCMAKE_CXX_COMPILER=${{ matrix.compiler }} -DCMAKE_BUILD_TYPE=Release
      - name: build
        run: cmake --build build --parallel 2
      - name: test
        run: cd build && ctest -j 2 --output-on-failure

  ci_test_standards:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        standard: [11, 14, 17, 20]
        compiler: [g++, clang++]
    steps:
      - uses: actions/checkout@v2
      - name: cmake
        run: cmake -S . -B build -DCMAKE_CXX_COMPILER=${{ matrix.compiler }} -DCMAKE_CXX_STANDARD=${{ matrix.standard }} -DCMAKE_BUILD_TYPE=Release
      - name: build
        run: cmake --build build --parallel 2
      - name: test
        run: cd build && ctest -j 2 --output-on-failure
