name: Windows

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  msvc2022:
    runs-on: windows-2022
    strategy:
      matrix:
        build_type: [Debug, Release]
        architecture: [Win32, x64]

    steps:
      - uses: actions/checkout@v4
      - name: cmake
        run: cmake -S . -B build -A ${{ matrix.architecture }}
      - name: build
        run: cmake --build build --config ${{ matrix.build_type }} --parallel 2
      - name: test
        run: cd build && ctest -j 2 -C ${{ matrix.build_type }} --output-on-failure

  clang-cl-11:
    runs-on: windows-latest
    strategy:
      matrix:
        architecture: [Win32, x64]

    steps:
      - uses: actions/checkout@v4
      - name: cmake
        run: cmake -S . -B build -A ${{ matrix.architecture }} -T ClangCL
      - name: build
        run: cmake --build build --config Debug --parallel 2
      - name: test
        run: cd build && ctest -j 2 -C Debug --output-on-failure
